### ISSUE TITLE
Equip problem

### ISSUE THREAD

**Issue by ghost** [Ariouz/NPCLib#2]
![image](https://user-images.githubusercontent.com/64412779/80508702-ae34d400-8978-11ea-8318-26ffe6614b55.png)

**Comment by Ariouz** [comment]
Just NPCSlot.... no getId()

**Comment by Ariouz** [comment]
I did a mistake in readme file by doing getId(), that's juste NPCSlot... That's my bad

**Comment by Ariouz** [comment]
And you need to equip the NPC after spawned it
